import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(scriptDirectory, "..");
const reviewsRoot = join(projectRoot, "reviews");
const outputFile = join(projectRoot, "app", "lib", "generated-reviews.ts");
const dailyReviewPattern = /^\d{4}-\d{2}-\d{2}\.md$/;
const weeklyReviewPattern = /^weekly\/\d{4}-W\d{2}\.md$/;

async function collectMarkdown(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(entries.map(async (entry) => {
    const fullPath = join(directory, entry.name);
    if (entry.isDirectory()) return collectMarkdown(fullPath);
    if (entry.isFile() && entry.name.endsWith(".md")) return [fullPath];
    return [];
  }));
  return files.flat();
}

const markdownFiles = (await collectMarkdown(reviewsRoot))
  .filter((file) => {
    const reviewPath = relative(reviewsRoot, file).replaceAll("\\", "/");
    return dailyReviewPattern.test(reviewPath) || weeklyReviewPattern.test(reviewPath);
  })
  .sort();
const entries = await Promise.all(markdownFiles.map(async (file) => {
  const source = await readFile(file, "utf8");
  const key = `reviews/${relative(reviewsRoot, file).replaceAll("\\", "/")}`;
  return [key, source];
}));

const generated = `// Generated by scripts/sync-reviews.mjs. Do not edit manually.\nexport const generatedReviews: Record<string, string> = ${JSON.stringify(Object.fromEntries(entries), null, 2)};\n`;
await mkdir(dirname(outputFile), { recursive: true });
await writeFile(outputFile, generated, "utf8");
console.log(`Synced ${entries.length} review files.`);
